### ISSUE TITLE
[Bug] can not write data to doris0.12

### ISSUE THREAD

**Issue by lijun816** [apache/incubator-doris-spark-connector#16]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

doris version:0.12
spark-doris-connector-3.1_2.12   version:1.0.1

### What's Wrong?

When I use spark-doris-connector write dataFrame to doris 0.12 , an error occurs(**"Connect to doris http://xx:8030/api/backends?is_alive=true failed."**),as shown in the figure below:
![1648548631(1)](https://user-images.githubusercontent.com/18097524/160588687-102429ab-89b7-47f7-8438-48e18b9bb8ce.png)

I guess it's because doris-0.12 has no such interface("api/backends" ),but the official website document says that it supports 0.12+.
![1648549088(1)](https://user-images.githubusercontent.com/18097524/160590091-f6c730ab-b79b-4806-a827-4dbe7a7a1743.png)

Hope to get a reply, thank you.

### What You Expected?

support doris 0.12+ or change the official website document

### How to Reproduce?

Use the official example to reproduce.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Wahno** [comment]
You can use this API /rest/v1/system?path=//backends. It can be work.

**Comment by lijun816** [comment]
> You can use this API /rest/v1/system?path=//backends. It can be work.

Thank you very much for your reply.

0.12 does not have this interface
I find this "/system?path=//backends" api , then get the backends by parsing HTML.

**Comment by Wahno** [comment]
> > You can use this API /rest/v1/system?path=//backends. It can be work.
> 
> Thank you very much for your reply.
> 
> 0.12 does not have this interface I find this "/system?path=//backends" api , then get the backends by parsing HTML.

I checked the fe commit log, 0.12 does not have this interface, you may need to upgrade the version.
